In [ ]:
#TASK 1
class Student:
  ID=0
  def __init__(self,name,dept,id,cg):
      self.name=name
      self.department=dept
      self.id=id
      self.cgpa=cg
      Student.ID+=1
  
  def get_details(self):
    print(f'ID:{Student.ID}\nName:{self.name}\nDepartment:{self.department}\nAge:{self.id}\nCGPA:{self.cgpa}')

  def from_String(my_str):
    list1= my_str.split('-')
    s= Student(list1[0],list1[1],list1[2],list1[3])
    return s

s1 = Student("Samin", "CSE", 21, 3.91)
s1.get_details()
print("-----------------------")
s2 = Student("Fahim", "ECE", 21, 3.85)
s2.get_details()
print("-----------------------")
s3 = Student("Tahura", "EEE", 22, 3.01)
s3.get_details()
print("-----------------------")
s4 = Student.from_String("Sumaiya-BBA-23-3.96")
s4.get_details()

ID:1
Name:Samin
Department:CSE
Age:21
CGPA:3.91
-----------------------
ID:2
Name:Fahim
Department:ECE
Age:21
CGPA:3.85
-----------------------
ID:3
Name:Tahura
Department:EEE
Age:22
CGPA:3.01
-----------------------
ID:4
Name:Sumaiya
Department:BBA
Age:23
CGPA:3.96

In [ ]:
#Task 2
class Assassin:
  total = 0

  def __init__(self,name,successrate):
    self.name=name
    self.sr=successrate
    Assassin.total+=1
  
  @classmethod
  def failureRate(cls,name,fr):
    cls.name=name
    cls.succrate=100 - fr
    return Assassin(cls.name,cls.succrate)
  @classmethod
  def failurePercentage(cls,name,fp):
    cls.name=name
    cls.succrate=100 - int(fp[0:2])
    return Assassin(cls.name,cls.succrate)

  def printDetails(self):
    print(f'Name: {self.name}\nSuccess rate: {self.sr}\nTotal number of Assasssin:{Assassin.total}')


john_wick = Assassin('John Wick',100)
john_wick.printDetails()
print('================================')
nagisa = Assassin.failureRate("Nagisa",20)
nagisa.printDetails()
print('================================')
akabane = Assassin.failurePercentage("Akabane", "10%")
akabane.printDetails()

Name: John Wick
Success rate: 100
Total number of Assasssin:1
================================
Name: Nagisa
Success rate: 80
Total number of Assasssin:2
================================
Name: Akabane
Success rate: 90
Total number of Assasssin:3

In [ ]:
#Task 3
class Passenger:
  count=0
  def __init__(self,name):
    self.name=name
    self.fare=450
    Passenger.count+=1

  
  def set_bag_weight(self,kg):
    self.weight = kg
    if kg<=50 and kg>=21:
      self.fare += 50
    elif kg>50:
      self.fare+=100
  

  def printDetail(self):
    print(f'Name:{self.name}\nBus Fare:{self.fare}')


print('Total Passenger:', Passenger.count)
p1 = Passenger('Jack')
p1.set_bag_weight(90)
p2 = Passenger('Carol')
p2.set_bag_weight(10)
p3 = Passenger('Mike')
p3.set_bag_weight(25)
print("=========================")
p1.printDetail()
print("=========================")
p2.printDetail()
print("=========================")
p3.printDetail()
print("=========================")
print('Total Passenger:', Passenger.count)

Total Passenger: 0
=========================
Name:Jack
Bus Fare:550
=========================
Name:Carol
Bus Fare:450
=========================
Name:Mike
Bus Fare:500
=========================
Total Passenger: 3

In [ ]:
#Task 4
class Travel:
  count=0
  def __init__(self,loc1,loc2):
    self.l1=loc1
    self.l2=loc2
    self.time=1
    Travel.count+=1

  def display_travel_info(self):
    return f'Source: {self.l1}\nDestination:{self.l2}\nFlight Time:{str(self.time)}:00'

  def set_time(self,time):
    self.time=time
  
  def set_destination(self,loc2):
    self.l2=loc2
  def set_source(self,loc1):
    self.l1=loc1

print('No. of Traveller =', Travel.count)
print("=======================")
t1 = Travel("Dhaka","India")
print(t1.display_travel_info())
print("=======================")
t2 = Travel("Kuala Lampur","Dhaka")
t2.set_time(23)
print(t2.display_travel_info())
print("=======================")
t3 = Travel("Dhaka","New_Zealand")
t3.set_time(15)
t3.set_destination("Germany")
print(t3.display_travel_info())
print("=======================")
t4 = Travel("Dhaka","India")
t4.set_time(9)
t4.set_source("Malaysia")
t4.set_destination("Canada")
print(t4.display_travel_info())
print("=======================")
print('No. of Traveller =', Travel.count)

No. of Traveller = 0
=======================
Source: Dhaka
Destination:India
Flight Time:1:00
=======================
Source: Kuala Lampur
Destination:Dhaka
Flight Time:23:00
=======================
Source: Dhaka
Destination:Germany
Flight Time:15:00
=======================
Source: Malaysia
Destination:Canada
Flight Time:9:00
=======================
No. of Traveller = 4

In [ ]:
#Task 5
class Employee:
  def __init__(self,name,workingPeriod):
    self.name=name
    self.workingPeriod=workingPeriod
  @classmethod
  def employeeByJoiningYear(cls,name,year):
    cls.name=name
    cls.year=year-2010
    return Employee(cls.name,cls.year)

  @staticmethod
  def experienceCheck(yr,gen):
    if yr<=2:
      if gen=='male':
        return 'He is not experienced'
      else:
        return 'She is not experienced'
    
    elif yr>=3:
      if gen=='male':
        return 'He is  experienced'
      else:
        return 'She is  experienced'


employee1 = Employee('Dororo', 3)
employee2 = Employee.employeeByJoiningYear('Harry', 2016)
print(employee1.workingPeriod)
print(employee2.workingPeriod)
print(employee1.name)
print(employee2.name)
print(Employee.experienceCheck(2, "male"))
print(Employee.experienceCheck(3, "female"))

3
6
Dororo
Harry
He is not experienced
She is  experienced

In [ ]:
#Task 6
class Laptop:
  laptopCount=0
  def __init__(self,name,count):
    self.name=name
    self.count=count
    Laptop.laptopCount+=self.count
  @staticmethod
  def advantage():
    print('Laptops are portable')
  @classmethod
  def resetCount(cls):
    cls.laptopCount=0

lenovo = Laptop("Lenovo", 5);
dell = Laptop("Dell", 7);
print(lenovo.name, lenovo.count)
print(dell.name, dell.count)
print("Total number of Laptops", Laptop.laptopCount)
Laptop.advantage()
Laptop.resetCount()
print("Total number of Laptops", Laptop.laptopCount)

Lenovo 5
Dell 7
Total number of Laptops 12
Laptops are portable
Total number of Laptops 0

In [ ]:
#Task 7
class Cat:
  Number_of_cats=0
  def __init__(self,color,work):
    self.color=color
    self.work=work
    Cat.Number_of_cats+=1

  @classmethod
  def no_parameter(cls):
    cls.color='White'
    cls.work='sitting'
    return Cat(cls.color,cls.work)
  
  @classmethod
  def first_parameter(cls,color):
    cls.color=color
    cls.work='sitting'
    return Cat(cls.color,cls.work)

  @classmethod
  def second_parameter(cls,work):
    cls.color='Grey'
    cls.work=work
    return Cat(Number_of_catscls.color)
  
  def changeColor(self,color):
    self.color=color

  def printCat(self):
    print(f'{self.color} cat is {self.work}')


print("Total number of cats:", Cat.Number_of_cats)
c1 = Cat.no_parameter()
c2 = Cat.first_parameter("Black")
c3 = Cat("Brown", "jumping")
c4 = Cat("Red", "purring")
c5 = Cat.second_parameter("playing")
print("=======================")
c1.printCat()
c2.printCat()
c3.printCat()
c4.printCat()
c5.printCat()
c1.changeColor("Blue")
c3.changeColor("Purple")
c1.printCat()
c3.printCat()
print("=======================")
print("Total number of cats:", Cat.Number_of_cats)

Total number of cats: 0
=======================
White cat is sitting
Black cat is sitting
Brown cat is jumping
Red cat is purring
playing cat is Grey
Blue cat is sitting
Purple cat is jumping
=======================
Total number of cats: 5

In [ ]:
#TASK 8
class Cylinder:
  radius = 5
  height = 18
  def __init__(self,rad,hgt):
    
    print(f"Default: radius={Cylinder.radius} height={Cylinder.height}")
    print(f"Updated: radius={rad} height={hgt}")
    self.radius = rad
    self.height = hgt
    Cylinder.radius = rad
    Cylinder.height = hgt

  @staticmethod
  def area(rad,hgt):
    x = 2*(3.1416)*rad**2 + 2*(3.1416)*rad*hgt
    print("Area:",x)

  @staticmethod
  def volume(rad,hgt):
    x = (3.1416)*rad**2*hgt
    print("Volume:",x)

  @classmethod
  def changeFormat(cls,s1):
    x,y = s1.split("-")
    obj = Cylinder(int(x),int(y))
    return obj

  @classmethod
  def swap(cls,rad,hgt):
    obj = Cylinder(hgt,rad)
    return obj

c1 = Cylinder(0,0)
Cylinder.area(c1.radius,c1.height)
Cylinder.volume(c1.radius,c1.height)
print("===============================")
c2 = Cylinder.swap(8,3)
c2.area(c2.radius,c2.height)
c2.volume(c2.radius,c2.height)
print("===============================")
c3 = Cylinder.changeFormat("7-13")
c3.area(c3.radius,c3.height)
c3.volume(c3.radius,c3.height)
print("===============================")
Cylinder(0.3,5.56).area(Cylinder.radius,Cylinder.height)
print("===============================")
Cylinder(3,5).volume(Cylinder.radius,Cylinder.height)

Default: radius=5 height=18
Updated: radius=0 height=0
Area: 0.0
Volume: 0.0
===============================
Default: radius=0 height=0
Updated: radius=3 height=8
Area: 207.3456
Volume: 226.1952
===============================
Default: radius=3 height=8
Updated: radius=7 height=13
Area: 879.648
Volume: 2001.1992
===============================
Default: radius=7 height=13
Updated: radius=0.3 height=5.56
Area: 11.045865599999999
===============================
Default: radius=0.3 height=5.56
Updated: radius=3 height=5
Volume: 141.372

In [ ]:
#TASK 9

In [ ]:
#TASK 10 (1st try)
class SultansDine:
  total_branch=0
  total_sell=0
  list1=[]
  list2=[]
  def __init__(self,loc1):
    self.loc1=loc1
    SultansDine.total_branch+=1
    SultansDine.list1.append(self.loc1)


  def sellQuantity(self,qnt):
    self.qnt=qnt
    if self.qnt<10 and self.qnt>0:
      self.Branch_sell=self.qnt*300
    elif self.qnt<20 and self.qnt>10:
      self.Branch_sell=self.qnt*350
    else:
      self.Branch_sell=self.qnt*400
    SultansDine.list1.append(self.Branch_sell)
    SultansDine.total_sell+=self.Branch_sell

  def branchInformation(self):
    print(f'Branch name:{self.loc1}\nBranch Sell:{self.Branch_sell}')
  

  @classmethod  
  def details(cls):
    print(f'Total Number of Branche(s): {cls.total_branch}\nTotal Sell: {cls.total_sell} Taka')
    for i in range(0,len(cls.list1)):
      if cls.total_sell==0:
        break
      else:
        for i in range(0,len(cls.list1),2):
          print(f'Branch Name: {cls.list1[i]}, Branch Sell: {cls.list1[i+1]}')
          print(f'Branch consist\'s of totals sell\'s:{(cls.list1[i+1]/cls.total_sell)*100}')



SultansDine.details()
print('########################')
dhanmodi = SultansDine('Dhanmondi')
dhanmodi.sellQuantity(25)
dhanmodi.branchInformation()
print('-----------------------------------------')
SultansDine.details()
print('========================')
baily_road = SultansDine('Baily Road')
baily_road.sellQuantity(15)
baily_road.branchInformation()
print('-----------------------------------------')
SultansDine.details()
print('========================')
gulshan = SultansDine('Gulshan')
gulshan.sellQuantity(9)
gulshan.branchInformation()
print('-----------------------------------------')
SultansDine.details()

Total Number of Branche(s): 0
Total Sell: 0 Taka
########################
Branch name:Dhanmondi
Branch Sell:10000
-----------------------------------------
Total Number of Branche(s): 1
Total Sell: 10000 Taka
Branch Name: Dhanmondi, Branch Sell: 10000
Branch consist's of totals sell's:100.0
Branch Name: Dhanmondi, Branch Sell: 10000
Branch consist's of totals sell's:100.0
========================
Branch name:Baily Road
Branch Sell:5250
-----------------------------------------
Total Number of Branche(s): 2
Total Sell: 15250 Taka
Branch Name: Dhanmondi, Branch Sell: 10000
Branch consist's of totals sell's:65.57377049180327
Branch Name: Baily Road, Branch Sell: 5250
Branch consist's of totals sell's:34.42622950819672
Branch Name: Dhanmondi, Branch Sell: 10000
Branch consist's of totals sell's:65.57377049180327
Branch Name: Baily Road, Branch Sell: 5250
Branch consist's of totals sell's:34.42622950819672
Branch Name: Dhanmondi, Branch Sell: 10000
Branch consist's of totals sell's:65.57377049180327
Branch Name: Baily Road, Branch Sell: 5250
Branch consist's of totals sell's:34.42622950819672
Branch Name: Dhanmondi, Branch Sell: 10000
Branch consist's of totals sell's:65.57377049180327
Branch Name: Baily Road, Branch Sell: 5250
Branch consist's of totals sell's:34.42622950819672
========================
Branch name:Gulshan
Branch Sell:2700
-----------------------------------------
Total Number of Branche(s): 3
Total Sell: 17950 Taka
Branch Name: Dhanmondi, Branch Sell: 10000
Branch consist's of totals sell's:55.71030640668524
Branch Name: Baily Road, Branch Sell: 5250
Branch consist's of totals sell's:29.247910863509752
Branch Name: Gulshan, Branch Sell: 2700
Branch consist's of totals sell's:15.041782729805014
Branch Name: Dhanmondi, Branch Sell: 10000
Branch consist's of totals sell's:55.71030640668524
Branch Name: Baily Road, Branch Sell: 5250
Branch consist's of totals sell's:29.247910863509752
Branch Name: Gulshan, Branch Sell: 2700
Branch consist's of totals sell's:15.041782729805014
Branch Name: Dhanmondi, Branch Sell: 10000
Branch consist's of totals sell's:55.71030640668524
Branch Name: Baily Road, Branch Sell: 5250
Branch consist's of totals sell's:29.247910863509752
Branch Name: Gulshan, Branch Sell: 2700
Branch consist's of totals sell's:15.041782729805014
Branch Name: Dhanmondi, Branch Sell: 10000
Branch consist's of totals sell's:55.71030640668524
Branch Name: Baily Road, Branch Sell: 5250
Branch consist's of totals sell's:29.247910863509752
Branch Name: Gulshan, Branch Sell: 2700
Branch consist's of totals sell's:15.041782729805014
Branch Name: Dhanmondi, Branch Sell: 10000
Branch consist's of totals sell's:55.71030640668524
Branch Name: Baily Road, Branch Sell: 5250
Branch consist's of totals sell's:29.247910863509752
Branch Name: Gulshan, Branch Sell: 2700
Branch consist's of totals sell's:15.041782729805014
Branch Name: Dhanmondi, Branch Sell: 10000
Branch consist's of totals sell's:55.71030640668524
Branch Name: Baily Road, Branch Sell: 5250
Branch consist's of totals sell's:29.247910863509752
Branch Name: Gulshan, Branch Sell: 2700
Branch consist's of totals sell's:15.041782729805014

In [ ]:
#TASK10
class SultansDine:
  total_branch=0
  total_sell=0
  branch_name={}
  def __init__(self,branch):
      self.branch=branch
      SultansDine.total_branch=SultansDine.total_branch+1
    
  def sellQuantity (self, qty):
      self.qty=qty
      if self.qty<10:
          self.branch_sell=self.qty*300
      elif self.qty<20 and self.qty>=10:
          self.branch_sell=self.qty*350
      else:
          self.branch_sell=self.qty*400

      SultansDine.total_sell=SultansDine.total_sell + self.branch_sell
      SultansDine.branch_name[self.branch]=self.branch_sell

  @classmethod
  def details(cls):
      if cls.total_branch == 0:
          print(f'Total Number of branch(s): {cls.total_branch}')
          print(f'Total Sell: {cls.total_sell} Taka')
      else:
          print(f'Total Number of branch(s): {cls.total_branch}')
          print(f'Total Sell: {cls.total_sell} Taka')

          for branches, sell in cls.branch_name.items():
              sell_percentage=(sell/cls.total_sell)*100
              sell_percentage=round(sell_percentage,2)
              print(f'Branch name: {branches}, Branch Sell: {sell} Taka, Branch consists of total sells: {sell_percentage}%')

  def branchInformation (self):
      print(f'Branch Name:{self.branch}')
      print(f'Branch Sell={self.branch_sell}')

SultansDine.details()
print('########################')
dhanmodi = SultansDine('Dhanmondi')
dhanmodi.sellQuantity(25)
dhanmodi.branchInformation()
print('-----------------------------------------')
SultansDine.details()
print('========================')
baily_road = SultansDine('Baily Road')
baily_road.sellQuantity(15)
baily_road.branchInformation()
print('-----------------------------------------')
SultansDine.details()
print('========================')
gulshan = SultansDine('Gulshan')
gulshan.sellQuantity(9)
gulshan.branchInformation()
print('-----------------------------------------')
SultansDine.details()

Total Number of branch(s): 0
Total Sell: 0 Taka
########################
Branch Name:Dhanmondi
Branch Sell=10000
-----------------------------------------
Total Number of branch(s): 1
Total Sell: 10000 Taka
Branch name: Dhanmondi, Branch Sell: 10000 Taka, Branch consists of total sells: 100.0%
========================
Branch Name:Baily Road
Branch Sell=5250
-----------------------------------------
Total Number of branch(s): 2
Total Sell: 15250 Taka
Branch name: Dhanmondi, Branch Sell: 10000 Taka, Branch consists of total sells: 65.57%
Branch name: Baily Road, Branch Sell: 5250 Taka, Branch consists of total sells: 34.43%
========================
Branch Name:Gulshan
Branch Sell=2700
-----------------------------------------
Total Number of branch(s): 3
Total Sell: 17950 Taka
Branch name: Dhanmondi, Branch Sell: 10000 Taka, Branch consists of total sells: 55.71%
Branch name: Baily Road, Branch Sell: 5250 Taka, Branch consists of total sells: 29.25%
Branch name: Gulshan, Branch Sell: 2700 Taka, Branch consists of total sells: 15.04%